default:
  STTS: FALSE
  per_room_time_threshold: .5 #!expr NA # .5 indicates staff must be in OR for > 50% of case duration
  shared_work_experience_window_weeks: 4 # number of prior weeks of cases to include in familiarity metric
  table_suffix: '_dyad_stts_fifty_perc_rt' # adds to end of base DB table to store familiarity metrics
  borg_table_suffix: '_borg_stts_allstaff'
  dyad_table_suffix: '_dyad_fifty_perc_rt'
  data_dir: 'data/OR_Team_Data'
  cases_file: 'All OR Cases.csv'
  providers_file: 'All OR Providers.csv'
  cpt_file: 'All OR Cases CPT Codes.csv'
